# Generated by Django 5.2.12 on 2026-04-24 00:20

from django.db import migrations
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

def load_sql(file):
    return (BASE_DIR / "sql" / file).read_text()

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(load_sql("vw_reportealpacas.sql")),
        migrations.RunSQL(load_sql("vw_reporteovinos.sql")),
        migrations.RunSQL(load_sql("vw_reportevacunos.sql")),
        migrations.RunSQL(load_sql("vw_unidades_produccion.sql")),
    ]