# Generated by Django 5.2.12 on 2026-04-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
    ]
