# Generated by Django 5.2.12 on 2026-04-28 15:14

from django.db import migrations
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

def load_sql(file):
    return (BASE_DIR / "sql" / file).read_text()

class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
    migrations.RunSQL(load_sql("vw_sanidad_animal.sql")),
    migrations.RunSQL(load_sql("vw_campania_desparacitacion.sql")),
]