# Generated by Django 5.2.12 on 2026-04-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20260428_0844'),
        ('reports', '0003_create_view_campania_desparasitacion'),
    ]

    operations = [
    ]
